# Generated by Django 4.0.6 on 2022-07-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_survey_options_survey_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='option1_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option2_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option3_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option4_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option5_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.CharField(max_length=2000),
        ),
    ]
