# Generated by Django 4.0.6 on 2022-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_option1_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
