# Generated by Django 4.0.6 on 2022-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allcounts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
